### ISSUE TITLE
Remove 'Add Node' in contextual menu

### ISSUE THREAD

**Issue by gidonkatten** [newcat/baklavajs#106]
In my application I have a sidebar which I add nodes from. Therefore I would like to remove the `Add Node` option which appears when right clicking the editor. 

I can stop the nodes from being able to be added by not registering them, however the `Add Node` option still appears, just with no items. Ideally I would like to provide `vuePlugin` with a custom implementation of `Editor` so that I can remove `Add Node` entirely but I don't think this is possible looking at the possible components here https://github.com/newcat/baklavajs/blob/dev/packages/baklavajs-plugin-renderer-vue/src/viewPlugin.ts#L40. 

Therefore I have resorted to providing a custom `ContextMenu` implementation which just filters out any item with the label `Add Node`. In my opinion this is quite a hacky solution so I was wondering if there is anything cleaner which I can do.

Thank you in advance!

**Comment by newcat** [comment]
Unfortunately there is no cleaner solution I can think of. The only other solution would be to copy the [Editor.vue](https://github.com/newcat/baklavajs/blob/dev/packages/baklavajs-plugin-renderer-vue/src/components/Editor.vue) and modify the context menu. Then you could use the custom component instead of `<baklava-editor />`. But IMO that solution is even worse, so I just mentioned it for the sake of completeness. You are probably better of with your current solution.

With version 2 of Baklava I plan to remove the context menu completely and use a sidebar / dedicated buttons for the functionality anyway; mostly for touch compatibility but also because the UX of the context menu approach is bad. But until v2 is released (which will probably still take half a year or so) you need to stick with your solution, unfortunately.

**Comment by Halinen** [comment]
@gidonkatten Hi! May I ask you about the details of customizing the `ContextMenu`? I want to remove `Copy Nodes` and `Paste Nodes` from the `ContextMenu`, but when I copy the `ContextMenu.vue` and import it, I have met many `ts`/`Eslint` problems. I'm too noob to fix it : (
If you still remember this project, can you share your solutions?
