### ISSUE TITLE
Disconnecting inputs doesn't clear their values

### ISSUE THREAD

**Issue by code-is-art** [newcat/baklavajs#120]
**Problem**
Disconnecting the input doesn't clear the interface input values. Must clear them out to their defaults after every onCalculate function.
for example
```javascript
// set default value here
.addInputInterface('Input', 'object-input', () => ({}), { type: 'O-IN' })
.onCalculate((node) => {
    // get input value
    let input = node.getInterface('Input').value
    // do work here ...
    // must do this or the value doesn't reset when input is disconnected
    node.getInterface('Input').value = {}
})
```
**Expected Behavior**
When inputs get disconnected they should reset to their default values if assigned or undefined if not assigned.

**Comment by newcat** [comment]
This is intentional since neither connecting nor disconnecting should change a node interface's value. You could implement such behaviour like this:

```js
.addInputInterface('Input', 'object-input', () => ({}), { type: 'O-IN', default: () => ({}) })

this.editor.events.removeConnection.addListener(this, (c) => {
    if (c.to.default) {
        c.to.value = c.to.default();
    }
});
```

Notice the `default` as an additional property, since the default value is not saved normally and therefore not accessible after a node interface has been created.
