### ISSUE TITLE
FeatureRequest: Dynamically allow changing nodes

### ISSUE THREAD

**Issue by DJManuel** [newcat/baklavajs#126]
Just started working with baklavajs, and it is a great project!

It would be nice however to allow to dynamically change the layout of a node during runtime.
Based on an IntegerOption or SelectOption have the number of outputs that have been entered / selected
For example:

```
  constructor() {
    super();
    this.type = 'SplitterNode';
    this.name = 'Splitter';
    this.addInputInterface('Source');
    this.addOption('NrOutputs', 'SelectOption', '4', undefined, {
      items: ['2', '4', '6', '8', '16'],
    });
  }
  calculate() {
    const outputs = this.getOptionValue('NrOutputs');
     outputs.forEach(() => {
       this.addOutputInterface('outputPort');
     });
  }
```
However, this example does not work, nor when just trying to add a single output (without the .forEach) in the calculate() function.

Use case for me: Not for passing "real data" through the nodes, just as a visual representation of systems / software connected to each other.
However this functionality could be useful for other use cases as well, where a calculation may output multiple results and these want to be received on multiple outputs, dynamically based on a selection done on the node.
This reduces the need to have dozens of nodes that do basically the same thing, but the only difference is the number of outputs.

Is that possible and within your scope of the project?
Thank you

**Comment by LukasLoeffler** [comment]
Hello Manuel,

I forked the official CodeSandbox and created an basic example how this feature could be implemented right now without updating the library. You can find the sandbox here: [Example Sandbox](https://codesandbox.io/s/baklavajs-example-forked-86hmr?file=/src/MultipleOutput.js)

Please keep in mind that this implementation is very basic and a little bit hacky. You can only increase the number of outputs. The [node](https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore/classes/Node#getInterface) page of the documentation contains all accessors and methods you may have to use to create a working node.

I hope that helps for the moment :)

**Comment by DJManuel** [comment]
Hello @LukasLoeffler ,

Thank you very much for this suggestion. 
Based on that, I've created a [fork of the Sandbox with added functionnality](https://codesandbox.io/s/baklavajs-example-forked-r58dt?file=/src/MultipleOutput.js).
I extended it so that not only adding outputs is possible, but also removing then (when selecting a smaller number in the selection). Additionally make the numbering more "human friendly" with starting at 1 instead of 0.

I completely understand that this is a bit hacky, however as an intermediate solution this works fine for me.
I am rather new to JS, so my implementation may not be that good.
Long-term it would be however very useful to have this functionality in the library itself.

Thank you very much!

**Comment by newcat** [comment]
Thanks for the quick answer, @LukasLoeffler. I have created a similar node in the playground: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-playground/src/AdvancedNode.ts

In your case it is even simpler, since you don't have buttons. So I have also created a node for your use-case in the playground: https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-playground/src/SplitterNode.ts

It is based on the idea of @LukasLoeffler and also supports removing of interfaces. As it is in TypeScript. I have transpiled it to JavaScript here:
<details>
<summary>JavaScript Splitter Node</summary>

```js
import { Node } from "@baklavajs/core";
export default class SplitterNode extends Node {
    constructor() {
        super();
        this.type = "SplitterNode";
        this.name = "Splitter";
        this.addInputInterface("Source");
        const nrOutputsOption = this.addOption("NrOutputs", "SelectOption", "4", undefined, {
            items: ["2", "4", "6", "8", "16"]
        });
        nrOutputsOption.events.setValue.addListener(this, () => {
            this.updateOutputs();
        });
        this.updateOutputs();
    }
    load(state) {
        state.interfaces.forEach(([name, intfState]) => {
            if (name.startsWith("Output")) {
                const intf = this.addOutputInterface(name);
                intf.id = intfState.id;
            }
        });
        super.load(state);
    }
    updateOutputs() {
        const numberOfOutputs = parseInt(this.getOptionValue("NrOutputs"), 10);
        const outputIntfs = Object.keys(this.outputInterfaces);
        if (outputIntfs.length > numberOfOutputs) {
            // we have more outputs than we need, remove some
            for (let i = numberOfOutputs + 1; i <= outputIntfs.length; i++) {
                this.removeInterface(`Output ${i}`);
            }
        }
        else if (outputIntfs.length < numberOfOutputs) {
            // we need more outputs
            for (let i = outputIntfs.length + 1; i <= numberOfOutputs; i++) {
                this.addOutputInterface(`Output ${i}`);
            }
        }
    }
}
```
</details>

---

> Long-term it would be however very useful to have this functionality in the library itself.

Unfortunately it is very difficult to cater for all those use-cases while still providing enough flexibility. For example, you might want to have a dynamic number of input interfaces instead of output interfaces, or you want to assign types to the interfaces, etc. So and API that covers all that would probably not be very easy to use.

But I do agree that the support for dynamic nodes needs to be improved somehow. Especially when it comes to saving and loading. I have a few ideas on how to do that, but since they require quite big changes, I will only consider them for BaklavaJS v2 (in which the complete options & interface API is overhauled anyway.)

**Comment by dev-dsp** [comment]
Is it possible to do the same without using TypeScript? I'd like to use "pure" js with this library, and would like to dynamically modify outputs based on input value.

**Comment by newcat** [comment]
Does the code I posted [here](https://github.com/newcat/baklavajs/issues/126#issuecomment-802418465) work for you? You need to click on "JavaScript Splitter Node" to expand it; then you'll see the JS code.
