### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by opl-** [newcat/baklavajs#15]
Setting up the environment to contribute to this project has proven itself more challenging than I anticipated. It would be useful to include a guide for new contributors to make their lives easier.

After some experimentation I came up with these commands, though I didn't end up setting up a webpack watcher to automatically rebuild the projects on changes. From my digging it doesn't seem this repo includes a quick way of doing that.

```bash
# Install Lerna (https://lerna.js.org/)
npm install -g lerna
# Download and setup the repo
git clone git@github.com:newcat/baklavajs.git
cd baklavajs
lerna bootstrap --npm-client=npm
# Build all the packages
lerna run build
# Run the playground (with npm)
cd packages/baklavajs-playground
npm run serve
# Run the playground (with yarn, from project's root directory)
npm run playground
```

**Comment by newcat** [comment]
Thanks for your contributions and your effort of trying to understand the project structure. I am not happy with the current structure, because it doesn't allow for efficient development. As soon as I rework the structure I will add the guide / some more general documentation to get contributors started quickly. I will leave this issue open until I added the guide.

**Comment by newcat** [comment]
Added an initial guide, which can be found here: https://newcat.github.io/baklavajs/#/contributing
Will do some refinement over time
