### ISSUE TITLE
Server side calculations

### ISSUE THREAD

**Issue by sysrun** [newcat/baklavajs#168]
Is it somehow possible to run calculations on the server side (async)?

**Comment by newcat** [comment]
Depends on what exactly you want to do with the calculations. It is not supported directly out of the box in Baklava V1. The easiest way to do a remote calculation is to:
1. Save the graph
2. Send the resulting JSON to the server, where you have a Baklava Instance with the Engine Plugin
3. Load the graph in the server's Baklava Instance
4. Run the calculation
5. (optional) If you want to display the calculation result inside the client (browser), you'd have to send the results back to the browser and display them there (e. g. save the graph on the server and load it in the browser; or implement a custom logic that sets node options / node interfaces to the desired values)

Of course, the node definitions must be accessible from both the client and the server. If you have a shared codebase for client and server this is easy - just define them in a central place and import them in both the client and the server. If you have a split codebase, it is more difficult and you either have to find a way to share the code or implement the nodes twice (although in that case the client part doesn't need to have the `calculate` function implement since it doesn't do any calculation).

**Comment by sysrun** [comment]
Thank you for your explanation :) I think using the `calculated` method will be the way to go
