### ISSUE TITLE
Adding custom HTML to node's

### ISSUE THREAD

**Issue by TomYeoman** [newcat/baklavajs#203]
I have a few cases, whereby I'd like to add some custom HTML elements to a node, however have it not reflect in the Baklava "save" structure.

**Some examples -**

- Display a message above a node depending on the result of some action 
- Hide/show a particular input, which could collect some data related to the node, however not necessarily be an "option" per say. 

Currently I have resorted to adding these HTML elements, as an option still to a particular node, but then I just filter out the option on "save".

```
export class Configuration extends Node {
  constructor() {
    super();
    this.type = "Configuration";
    /*
        This will ALWAYS exist as an option on every configuration
        however sometimes it will sometimes be hidden
    */
    this.addOption("RemoveOnSave", "TestResultMessage");
  }
}
```

On save - 
```
let graphSaveRequest = axios
  .create()
  .put(this.$route.path, {
    graph: (() => {
      return {
        ...workflow,
        nodes: workflow.nodes.map(node => {
        return {
          ...node,
          // When we save the graph to backend, we filter out these "options" from the baklava graph structure.
          options: node.options.filter(options => {
            return !options.includes("TestResultMessage");
          })
        };
      };
    })()
  })
```

Is there a better way to achieve this, without this work around?

- Can I add custom HTML to a custom node, without having to create an option?
- Can I extend the "base node" and add custom HTML?

Thanks!

**Comment by newcat** [comment]
I guess the easiest way is indeed to use a custom Node component. Here is an example of a custom implementation: https://github.com/icivann/ivann/blob/master/src/baklava/CustomNode.vue

The way Vue works, you have to unfortunately copy the [original HTML](https://github.com/newcat/baklavajs/blob/master/packages/baklavajs-plugin-renderer-vue/src/components/node/Node.vue), but if you are using `vue-property-decorator` and `vue-class-component`, you can at least extend the JS/TS part so you don't have to copy that as well.

Then you can just tell Baklava to use your custom Node component instead of the original one:
```js
const view = new ViewPlugin();
view.components.node = CustomNode;
```
