### ISSUE TITLE
Laggy rendering

### ISSUE THREAD

**Issue by mleonowicz** [newcat/baklavajs#215]
When moving a node fast the rendered connections are out of place. It looks like the connections and nodes are rendered for different cursor positions. I have hardware acceleration enabled. I tested it both on Firefox and Chromium on different machines.

Example:
![image](https://user-images.githubusercontent.com/16629118/192249660-d28af3ee-d0e5-4fc0-90bf-c270a7057d52.png)

**Comment by mleonowicz** [comment]
I see that it has been fixed here: https://github.com/newcat/baklavajs/commit/8ad369d0e7206c7685fb96f86e5a8ffac6e4d613 and after building the library myself the laggy rendering is gone.
Is the current master branch going to be available in npm repository?

Thanks in advance

**Comment by newcat** [comment]
Unfortunately I don't have much time for my side-projects like Baklava at the moment but I should be able to do the release next week (need to do some testing and documentation beforehand, that's why I can't release it just yet). And thanks for going through the hassle of building / testing the current master and verifying that the issue is fixed there; I really appreciate it.
