### ISSUE TITLE
Baklavajs V2 Unable to load saved state - Critical Issue

### ISSUE THREAD

**Issue by MioAtSwivel** [newcat/baklavajs#226]
Currently the setup is that we have the frontend editor making the graph, save it to mongodb and run the graph with a nodejs server.

Loading the graph inside nodejs is not an issue, and the graph runs normally. However loading the same graph in the frontend resulted in type error originating from the library, and refuse to load the rest of the graph.

I have checked that there is no typing problem on my own code, and the object passed to the load function is indeed the `IEditorState` interface type
![image](https://user-images.githubusercontent.com/102662641/202409384-31aa9e30-868c-41b2-861d-b8f3e7d7d723.png)

**Comment by MioAtSwivel** [comment]
Extra information regarding this issue, when I do JSON parse on a JSON stringified graph that has a subgraph, it is loading back properly, but not any case else

**Comment by newcat** [comment]
Unfortunately, I am not able to reproduce this issue. Can you
1. try whether this might be fixed with the new beta version [v2.0.2-beta.1](https://github.com/newcat/baklavajs/releases/tag/v2.0.2-beta.1) (I honestly doubt it, but it's worth a try)
2. create a repo/sandbox which reproduces the error? Or give specific steps on how to reproduce it

**Comment by MioAtSwivel** [comment]
It was caused by the misuse of vue2's composition API, the problem does not happen on a full vue3 environment.
