### ISSUE TITLE
[V2] Subgraph input / output nodes changing position after editing subgraph

### ISSUE THREAD

**Issue by hthomas92** [newcat/baklavajs#244]
The subgraph input / output nodes change position after editing an existing subgraph

Repro steps:
1. Create a subgraph (with multiple inputs and outputs)
2. Wire the nodes, save and go back to the main graph
3. Edit the subgraph. After this step, all input and output nodes will be moved to the top left area in the editor and share the same position overlapping each other.

**Comment by newcat** [comment]
This is (kind of) intended. As of now, I haven't implemented the necessary functionality for that. It is also not super trivial, since the input/output nodes are dynamically generated whenever the subgraph is being displayed and so they aren't saved. I'll think about a nice solution to this issue, but I admit that it doesn't have the highest priority at the moment.

**Comment by hthomas92** [comment]
I see... that also explains the behavior that if I wire two nodes to the same input node, then the input nodes will be duplicated after I reopen the subgraphs.

From a user's perspective, if I created a sub-graph and arranged all my nodes and wires there, including the input and output nodes, it would be nice to see the exact same layout every time I open the graph.

So I'd save the input and output nodes, and only generate them when the subgraph is created for the first time. In all other cases the user can place or delete them manually if needed.
