### ISSUE TITLE
Prevent delete?

### ISSUE THREAD

**Issue by CTB-Software** [newcat/baklavajs#245]
is there a way to prevent a node from being deleted?

**Comment by newcat** [comment]
Yes:

## v1:
- [Event System](https://newcat.github.io/baklavajs/#/event-system?id=events)
- [Relevant Event](https://newcat.github.io/baklavajs/api/index.html#/@baklavajs%2Fcore/classes/Editor#beforeRemoveNode)

Example:
```js
const token = Symbol();
editor.events.beforeRemoveNode.addListener(token, () => false);
```

## v2:
- [Event System](https://v2.baklava.tech/event-system.html#events)
- [Relevant Event](https://v2.baklava.tech/api/classes/_baklavajs_core.Editor.html#graphEvents)

Example:
```js
const token = Symbol();
editor.graphEvents.beforeRemoveNode.subscribe(token, (data, prevent) => prevent());
```

**Comment by alexisrolland** [comment]
@newcat Actually I have one more question related to this... I still want users to be able to delete nodes by doing right click on title > delete. But our graphs has an annoying when editing text in node options. If the user press the DEL key on his keyboard, the entire node is deleted rather than just the text in the text area.

I'm not sure if this is a bug related to our implementation (we use Ant Design for Vue.js to create node options), or if this is a bug with Baklava. I think just having a way to deactivate the delete keyboard shortcuts could do the trick. Is there a solution to do this?

Many thanks <3

**Comment by alexisrolland** [comment]
Additional comment to say I was able to reproduce the issue in the Baklava demo as follow: 
https://codesandbox.io/s/baklavajs-example-forked-twsd1r?file=/src/MathNode.js

- Added an `InputOption` in the `MathNode`
- Click on the title of the `MathNode` to select the node
- Double click on the text in the text input to select the word
- Press Delete key --> the whole node is deleted
