### ISSUE TITLE
Suggestion: context menu styling

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#32]
Perhaps include `category-<id>` and `item-<node type>` CSS classes in context menus, so, for example, list items can inherit the color of the node itself. I'd make a PR, but it seems the context menu doesn't get passed any node data, so I'll leave that decision up to you.

Also, hide the divider if no categories or no default nodes exist

**Comment by newcat** [comment]
"context menu doesn't get passed any node data" that's why I probably won't implement this. If I wanted to do so, I'd need to create a separate and non-reusable context menu component which I don't want to at this point. But the divider will be hidden in future versions.

**Comment by Stumblinbear** [comment]
Moved from #27 because I'm stupid:

Perhaps then a way to resolve the issue would be to add a hook for context menu creation so that users can alter the entries themselves as necessary. Then, I can use my own internal grouping system by looking up the type and add CSS classes as I see fit. I already do this for nodes themselves, and now connections. Doing it for the context menu doesn't seem like too much of a stretch, at this point.

I don't recall if there is a hook, admittedly. Though, I'm leaning towards there not being, as I'd probably have seen it and would be using it if there was :P

**Comment by newcat** [comment]
Hooks are difficult due to the recursive nature of context menus. I suggest using a custom component like in https://github.com/newcat/baklavajs/issues/25#issuecomment-516184738 for the custom context menu. You can take the [original context menu component](https://github.com/newcat/baklavajs/blob/dev/packages/baklavajs-plugin-renderer-vue/src/components/ContextMenu.vue) as a starting point.
