### ISSUE TITLE
Suggestion: Use node name instead of type for context menu

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#36]
In my opinion, it would look much much nicer.

![image](https://user-images.githubusercontent.com/11092351/62048334-3875bf00-b1d2-11e9-9786-5932f45f8173.png)

![image](https://user-images.githubusercontent.com/11092351/62048354-4d525280-b1d2-11e9-9be2-bb064ddff96d.png)

In my case, the type ID must be in that format for consistency and loading purposes.

Is there any reason type is used instead of the node name, currently?

**Comment by newcat** [comment]
Umm okay. Originally the type was thought of as the name of a node. The reason for the additional `name` property in the node class is just so that users can give their own names to users, which is useful when you have a lot of nodes with the same type in a graph. But I see that quite a few people use the `type` property more as a type identifier and the `name` property as more of a "human readable type". Which I do understand, but that is the reason that some of the decisions regarding that topic might seem strange. Probably related to #37 as well.

I will change that behaviour in the context menu and use the `name` instead of the `type` (which is probably not even a breaking change, since my recommendation in the docs was to set the `name` field to the value of `type` by default)

**Comment by Stumblinbear** [comment]
Perhaps it's because of the way you named the fields. If it was name and displayName, perhaps they'd have been used differently. I assumed `type` was for internal usage so that saving and loading could work correctly.

**Comment by newcat** [comment]
I probably wrote my comment a bit prematurely, since I just noticed that it's not that easy. The `name` property does only exist on node instances, so when creating the context menu instances I don't have access to it. I also don't want to create an instance of every node just for getting the default name as this could cause side effects. So instead, I added the `setNodeTypeAlias` function to the `ViewPlugin` class: https://github.com/newcat/baklavajs/blob/dev/packages/baklavajs-plugin-renderer-vue/src/viewPlugin.ts#L98

I know this isn't ideal, but the best solution I could think of
