### ISSUE TITLE
See Previous Bug #327 - Weird Precision Issues persisting with v2.3

### ISSUE THREAD

**Issue by sgramsay** [newcat/baklavajs#367]
![image](https://github.com/newcat/baklavajs/assets/25171653/94a4dbba-24dd-47a0-9bbd-7da9ac437330)
Output from final Math node outputs incorrect value to displayNode

Uses Version 2.3

**Comment by newcat** [comment]
Unfortunately, this is a JavaScript or rather a floating point problem. When you type `(1.3+10.0)+(1.4+10.5)` into a NodeJS/browser console, you'll see the same output. And since the `TextInterface` just displays the incoming value as a string, there isn't a way around this problem.

If needed, you can create your own interface that shows numbers by rounding them, but I'd consider this out-of-scope for a simple text display interface.
