### ISSUE TITLE
Input and output nodes cannot share the same name

### ISSUE THREAD

**Issue by Stumblinbear** [newcat/baklavajs#39]
While I can sort of understand why, you use one Object for interfaces, however this seems very limiting and unnecessary.

**Comment by newcat** [comment]
Yeah had separate maps/objects in earlier versions but for most use-cases it was just a hassle, so I decided to merge them into a single object. What I can do (and probably will do, but it's a breaking change, so it may take more time due to testing) is to give interfaces an additional `name` property, that is independent of the key in the `interfaces` object. This will also allow multiple input interfaces or multiple output interfaces with the same name, which might come in handy.

**Comment by Stumblinbear** [comment]
I agree completely. I have a few things that benefit from expanding input/output interfaces, but having to rename them on each one makes it look a bit odd. Also, my system uses an execution flow, so the input and output nodes are named `Execute`. Except, of course, I can't do that, so I went with `Execute` and `Completed` except sometimes when I can't because it doesn't make sense..

**Comment by carbotaniuman** [comment]
Any updates to this? Any way I can help development on this?

**Comment by newcat** [comment]
This will be the next feature I am going to work on. Should be done in the next few days, at least in the @next channel (dev branch).

**Comment by newcat** [comment]
Implemented in a17cacfa05e1115fc1665fb784a4cf9e6136b78f using the new additional property `displayName`. Example: https://github.com/newcat/baklavajs/blob/dev/packages/baklavajs-playground/src/MathNode.ts#L4

**Comment by carbotaniuman** [comment]
@newcat So how would I do this - make the interface name `nameOut` and `nameIn` and set displayName to `name`?

**Comment by newcat** [comment]
Correct, it should work like that.
