### ISSUE TITLE
Can we have bidirectional ports? 

### ISSUE THREAD

**Issue by nikitagirase11** [newcat/baklavajs#395]
Can we have bidirectional ports? it we very annoying that if we 6 input then adding 6 output node will become huge?/
@newcat please help

**Comment by newcat** [comment]
Internally, inputs and outputs have to be separated as the whole logic is built around that. However, you can use a [custom node component](https://v2.baklava.tech/visual-editor/customization.html#custom-components) to change how interfaces are rendered. I don't think I can implement this in the base library very well since there will be a ton of edge cases that'd need to be handled.
