### ISSUE TITLE
 How to get the number of computational processes (or named functions, algorithms) in a graph

### ISSUE THREAD

**Issue by chuteany** [newcat/baklavajs#400]
How to get the number of computational processes (or named functions, algorithms) in a graph—for example, the graph below contains two, the number is two. And how to get some one of them

![image](https://github.com/newcat/baklavajs/assets/152139999/6fc0dd60-1f2f-49b2-a93b-46488824c344)

**Comment by newcat** [comment]
Baklava doesn't calculate this, since it is only concerned about the order in which nodes have to be executed. But you can use a simple BFS or DFS algorithm to compute the number of isolated parts in the graph. Have a look at this SO question, for example: https://stackoverflow.com/questions/1348783/finding-all-disconnected-subgraphs-in-a-graph

**Comment by chuteany** [comment]
thank you!
