### ISSUE TITLE
Mobile devices friendly

### ISSUE THREAD

**Issue by tpoxa** [newcat/baklavajs#66]
Hi, @newcat thank you for your work. Any plans to make Baklava.js working on mobile devices?
Currently it does not pan. Nodes dragging does not work also...

**Comment by newcat** [comment]
Yes this is planned for v2.0. But I am not sure if this library will really work for smartphones, because the screen is just too small to be really usable. Instead, I am planning to add touch support for tablets and laptops with touchscreens. This means adding the ability to drag nodes and pan/zoom, but also changing everything that is currently done via context menus. For example, I'll be adding a sidebar, from which new nodes can be created, instead of having to right-click to add new nodes.
